name: Scrape ATU_GobPeru Twitter Account

on:
  schedule:
    - cron: "*/15 * * * *"
 
jobs:
  cron:
    runs-on: ubuntu-22.04
 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Scrap account
        run: |
          npm run scrape
          git config user.name dl-alert-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update ATU_GobPeru database"
          git push origin main
